### ISSUE TITLE
Can't update nor run on MacOS 10.13?

### ISSUE THREAD

**Issue by cviebrock** [Jackett/Jackett#15880]
### Have you checked our Troubleshooting page for your issue?

- [x] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [x] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [x] I have read the Contributing Guidelines

### Environment

```markdown
Can't check since I can't get it running.
```

### Description

Updating Jackett v0.21.2943 on my Mac Mini (running MacOS 10.13.6 on Intel hardware) wasn't working, so I uninstalled and reinstalled according to the directions.  System logs showed this repeatedly:

```
Feb 27 14:04:19 Mini com.apple.xpc.launchd[1] (org.user.Jackett): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
```

Looking through an [old issue](https://github.com/Jackett/Jackett/issues/5062), it was suggested I stop the service and launch Jackett manually, which resulted in:

```
>./jackett -t -l
dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/cmv/Jackett/./jackett (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/cmv/Jackett/./jackett
```

So ... does the latest version of Jacket not run on MacOS 10.13 anymore?  I don't immediately see anything in the release notes for when this might have stopped working, so I'm not sure what version I need to revert to.

### Logged Error Messages

```text
dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/cmv/Jackett/./jackett (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/cmv/Jackett/./jackett
```

**Comment by garfield69** [comment]
Jackett is dependant of .NET8 which is supported only from MacOS 13.0+ onwards.
https://github.com/dotnet/core/blob/main/release-notes/8.0/supported-os.md#apple

**Comment by cviebrock** [comment]
Thanks @garfield69.  I've since switched back to v0.21.2943 which continues to work.  I'm assuming that's the last version of Jackett that uses the older version of .NET (and so will still work on MacOS 10.13)?

Might I suggest updating Jackett's `README.md` file to indicate the minimum version of MacOS that's required for each release?  Thanks!

**Comment by garfield69** [comment]
Take a look at https://github.com/Jackett/Jackett#supported-systems, that section was updated at the start of January.
Don't forget to turn off the auto-update on the Jackett dashboard.
And you can manually update whichever indexers you use if they are out of date, by copying the source from https://github.com/Jackett/Jackett/tree/master/src/Jackett.Common/Definitions to your Definitions folder, although expect some to fail if they take advantage of features that 0.21 does not know about.

**Comment by cviebrock** [comment]
Ah sorry ... must have missed that section.  And yes, I'll turn the auto-updater off.  Thanks again!
